os: linux
dist: trusty
# See https://github.com/travis-ci/travis-ci/issues/8378 ; remove later
group: deprecated-2017Q3
python:
    - '3.6'
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y asciidoc cmake cmake-data cpanminus gperf libgmp-dev libgoogle-perftools-dev libperl-dev mercurial ninja-build python3 python3-setuptools perl python3-pip silversearcher-ag valgrind wget wml
    - ((mkdir emsdk && pushd emsdk && wget https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz && tar -xf emsdk-portable.tar.gz && pushd emsdk-portable && ./emsdk update && ./emsdk install latest && ./emsdk activate latest && popd && popd ) > /dev/null) && pwd
      # Temporary workaround for a problem in running the Inline::C test
      # suite with latest EU::MM - install Inline::C with no tests.
      #     - https://github.com/ingydotnet/inline-c-pm/issues/49 .
    - sudo cpanm --notest Alien::Tidyp Inline::C
      # Speed up installing the deps.
    - sudo cpanm --notest File::ReadBackwards Pod::Xhtml Task::FreecellSolver::Testing Task::Sites::ShlomiFish Text::WrapAsUtf8
    - bash fc-solve/scripts/install-git-cmakey-program-system-wide.bash 'git' 'installer' 'https://github.com/thewml/latemp.git'
    - ( cd .. && hg clone https://shlomif@bitbucket.org/shlomif/wml-extended-apis && cd wml-extended-apis/xhtml/1.x && bash Install.bash )
    - ( cd .. && hg clone https://shlomif@bitbucket.org/shlomif/wml-affiliations && cd wml-affiliations/wml && bash Install.bash )
    - ( cd .. && hg clone https://shlomif@bitbucket.org/shlomif/latemp && cd latemp/support-headers && perl install.pl )
install:
    - ls /home/travis/build/shlomif/fc-solve/fc-solve/source/../site/wml/../../source/main.c || true
    - ls /home/travis/build/shlomif/fc-solve/fc-solve/source/../site/wml/../../source/*.[ch] || true
    - which python3
    - python3 --version
    - sudo -H `which python3` -m pip install cffi
    - sudo -H `which python3` -m pip install random2
    - sudo -H `which python3` -m pip install Zenfilter
    - wget http://web-cpan.shlomifish.org/downloads/libtap-1.12.0.tar.bz2
    - tar -xvf libtap-1.12.0.tar.bz2
    - ( mkdir B && cd B && cmake ../libtap-1.12.0 && make && sudo make install )
    - ( a="$(pwd)"; mkdir B2 && cd B2 && hg clone https://bitbucket.org/shlomif/shlomif-cmake-modules && cd shlomif-cmake-modules/shlomif-cmake-modules && cp -f "$(pwd)"/Shlomif_Common.cmake "$a"/fc-solve/source/cmake/ )
perl:
    - "5.24"
python:
    - "3.5"
script:
    - export FC_SOLVE__MULT_CONFIG_TESTS__TRACE=1 FC_SOLVE__MULT_CONFIG_TESTS__DOCKER=1 ; set -o pipefail ; cd fc-solve/source ; . /home/travis/build/shlomif/fc-solve/emsdk/emsdk-portable/emsdk_env.sh && perl ../scripts/multi_config_tests.pl 2>&1 | zenfilter --count-step=500 --last=500 --filter='^Running:.*?\[\s*idx\s*=\s*[0-9]+\s*/\s*[0-9]+'
sudo: required
